version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install    
  build:
    commands:
      - npm run build
      - cd build && zip -r ./build.zip .
      - aws s3 cp build.zip s3://amplifybuild/build/dev/
  post_build:
    commands:
      - aws amplify start-deployment --app-id d3v4ja4ck1aigd --branch-name dish --source-url s3://amplifybuild/build/dev/
      
