version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
      - aws --version
  build:
    commands:
   #   - COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
   #   - echo $COMMIT
   #   - TAG=$(git describe --tags --exact-match --abbrev=7 $COMMIT)
   #   - echo "Current tag is $TAG"
      - npm run build
      - cd build && zip -r ./build-$TAG.zip .
      - aws s3 cp build-$TAG.zip s3://cbo-prod-bucket-1/UI-Build-files/
  post_build:
    commands:
      - aws amplify start-deployment --app-id d3v4ja4ck1aigd --branch-name dish --source-url s3://cbo-prod-bucket-1/UI-Build-files/build-$TAG.zip
   #   - aws amplify start-deployment --app-id d3v4ja4ck1aigd --branch-name prod --source-url s3://amplifybuild/build/dev/build-artifact.zip
   
      
      
      
      
      
