version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT
      - git config --list
   #   - git clone https://github.com/dishotham/AmplifyApp-sample.git
   #   - git config --global credential.helper "store --file ~/.git-credentials"
      - echo -e "protocol=https\nhost=github.com\nusername=${GIT_USERNAME}\npassword=${GIT_PASSWORD}" > ~/.git-credentials
   #   - chmod 0600 ~/.git-credentials
      - bash codebuild-git-wrapper.sh https://github.com/dishotham/AmplifyApp-sample.git main
      - git log | head -100
     # - TAG=$(git describe --tags --exact-match --abbrev=7 $COMMIT)
     # - echo "Current tag is $TAG"
      - npm install
  build:
    commands:
      - COMMIT=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT
      - TAG=$(git describe --tags --exact-match --abbrev=7 $COMMIT)
      - echo "Current tag is $TAG"
      - npm run build
      - cd build && zip -r ./build-$TAG.zip .
      - |
        if [ "$QA_Deploy" = "true" ]; then
          echo "Starting QA Deployment"
          aws amplify start-deployment --app-id dlkkiwthevzqo --branch-name dev109 --source-url s3://onecbo-build-artifacts/UI-Build-files/build-$TAG.zip;
        else
          echo "QA_Deploy is not set to true, skipping deployment";
        fi
      - echo "Copying build artifacts to S3 bucket"
      - aws s3 cp build-$TAG.zip s3://cbo-prod-bucket-1/UI-Build-files/
   
   
   
   
   
   
      
      
      
      
      
